title: Why Neural Net Works
description: Explaining and presenting interactive Neural Network techniques.
baseurl: ""
url: "http://****.github.io"
theme: minima

markdown: kramdown
plugins:
  - jekyll-feed

collections:
  projects:
    output: true

sass:
  sass_dir: _sass
  style: compressed # or nested, expanded, compact, as per your preference


# Custom settings
excerpt_separator: "<!--more-->"